server:
  port: 9009

spring:
  application:
    name: movie-booking

  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

